---
# Homepage configuration
# See https://fontawesome.com/search for icons options

title: "Dashboard"
subtitle: "Home"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: '<p>Homepage for tools hosted by Dheeth with <span class="has-text-danger">❤️</span>' # set false if you want to hide it.

# Optional theme customization
theme: default

columns: "3"

defaults:
  layout: list

# Optional message
message:
  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  title: "👋 Welcome!"
  content: "This is a Dashboard created to list down all the services hosted on HomeLab"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Contribute!"
    icon: "fab fa-github"
    url: "https://github.com/dheeth/homer/blob/main/public/assets/config.yml"
    target: "_blank" # optional html a tag target attribute
  - name: "Blog"
    icon: "fas fa-book"
    url: "https://dheeth.blog"
    target: "_blank"
  # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:
  # - name: "another page!"
  #   icon: "fas fa-file-alt"
  #   url: "#additional-page" 

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Hosted Tools"
    icon: "fa-solid fa-arrow-right"
    items:
      - name: "Jellyfin"
        logo: "https://github.com/jellyfin/jellyfin-ux/raw/refs/heads/master/branding/SVG/icon-solid-black.svg"
        # subtitle: "Watch Movies, Series all at the comfort of Home"
        tag: "media"
        type: "Emby"
        libraryType: "movies"
        url: "http://jellyfin.dheeth.local:8096"
        target: "_blank"
        apikey: "6b8331abafe2435991c79f21565e920f"
      - name: "Configuration"
        icon: "fa-solid fa-sliders"
        subtitle: "Configuration options documentation"
        tag: "setup"
        url: "https://github.com/bastienwirtz/homer/blob/main/docs/configuration.md"
      - name: "Theming"
        icon: "fa-solid fa-palette"
        subtitle: "Customize Homer appearance"
        tag: "theming"
        url: "https://github.com/bastienwirtz/homer/blob/main/docs/theming.md"
      - name: "Smart cards"
        icon: "fa-solid fa-palette"
        subtitle: "Displays dynamic information or actions."
        tag: "setup"
        url: "https://github.com/bastienwirtz/homer/blob/main/docs/customservices.md"
      - name: "Dashboard icons"
        icon: "fa-solid fa-icons"
        subtitle: "Dashboard icons"
        tag: "setup"
        url: "https://github.com/walkxcode/dashboard-icons"
      - name: "Buy me a coffee!"
        subtitle: "Sponsor this project"
        icon: "fa-solid fa-mug-hot"
        url: "https://www.buymeacoffee.com/bastien"
  - name: "Smart cards showcase"
    icon: "fa-solid fa-brain"
    class: "highlight-purple"
    items: 
      - name: "Octoprint"
        logo: "https://cdn-icons-png.flaticon.com/512/3112/3112529.png"
        apikey: "xxxxxxxxxxxx"
        endpoint: "/dummy-data/octoprint"
        type: "OctoPrint"
      - name: "Pi-hole"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/pi-hole.png"
        url: "https://pi-hole.net/"
        endpoint: "/dummy-data/pihole"
        type: "PiHole"
      - name: "Proxmox - Node1"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/proxmox.png"
        type: "Proxmox"
        tag: "sys"
        url: "https://www.proxmox.com/en/"
        endpoint: "/dummy-data/proxmox"
        node: "node1"
        warning_value: 50
        danger_value: 80
        api_token: "xxxxxxxxxxxx"
      - name: "PeaNUT"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@master/png/peanut.png"
        url: "https://github.com/Brandawg93/PeaNUT"
        endpoint: "/dummy-data/peanut"
        type: "PeaNUT"
        device: "ups"
      - name: "Weather"
        location: "Lille"
        apikey: "xxxxxxxxxxxx" # insert your own API key here. Request one from https://openweathermap.org/api.
        units: "metric"
        endpoint: "/dummy-data/openweather/weather"
        type: "OpenWeather"
  - name: "Ressources"
    icon: "fa-regular fa-bookmark"
    class: highlight-inverted
    items:
      - name: "r/selfhosted"
        icon: "fa-brands fa-reddit-alien"
        subtitle: "selfhosted community on Reddit"
        tag: "community"
        url: "https://www.reddit.com/r/selfhosted/"
        target: "_blank"
      - name: "c/selfhosted"
        logo: "https://icons.iconarchive.com/icons/simpleicons-team/simple/256/lemmy-icon.png"
        subtitle: "selfhosted community on Lemmy"
        tag: "community"
        url: "https://lemmy.world/c/selfhosted"
        target: "_blank" 
      - name: "Awesome selfhosted"
        icon: "fa-solid fa-star"
        subtitle: "Another application"
        tag: "awesome-list"
        url: "https://github.com/awesome-selfhosted/awesome-selfhosted"
